package:
  name: ninja_shogun
  version: "0.0.1"

source:
  git_url: https://github.com/bhillmann/NINJA-DOJO.git
  git_rev: 2f3482154828a502cf3348e56fb1b067a2b590e2

requirements:
  build:
    - python
    - setuptools
    - scipy
    - numpy
    - pandas
    - click
  run:
    - python

    
about:
  license: BSD
  license_file: COPYING.txt
