{% set version = "v0.99.7f" %}

package:
  name: burst
  version: "{{ version }}"

source:
  fn: burst-{{ version }}-linux-64.tar.gz #[linux]
  url: https://github.com/knights-lab/BURST/releases/download/{{ version }}/burst-{{ version }}-linux-64.tar.gz #[linux]
  sha256: 1c525c46340e8600a1414827538b5110340f68fb907cc635efc0712beba0cfe2   #[linux]

requirements:
  build:
  run:

about:
  summary: An ultrafast optimal aligner for mapping large NGS data to large genome databases.
  home: https://github.com/knights-lab/BURST
  license: AGPL
