package:
  name: burst
  version: "0.99.4a"

source:
  fn: burst-v0.99.4a-linux-64.tar.gz #[linux]
  url: https://github.com/knights-lab/BURST/releases/download/v0.99.4a/burst-v0.99.4a-linux-64.tar.gz #[linux]
  sha256: 2249b8e9a1cd11647b1855474e45dba2aefea630707dc5c48297b2ff6680d142 #[linux]

requirements:
  build:
  run:
  - python >= 2.7
  - bowtie2

about:
  summary: An ultrafast optimal aligner for mapping large NGS data to large genome databases.
  home: https://github.com/knights-lab/BURST
  license: AGPL

test:
  commands:
  - burst15 --help