{% set version = "1.0" %}

package:
  name: burst
  version: "{{ version }}"

source:
  fn: burst-{{ version }}-linux-64.tar.gz #[linux]
  url: https://github.com/knights-lab/BURST/releases/download/v{{ version }}/burst-v{{ version }}-linux-64.tar.gz #[linux]
  sha256: 1589a9551962432b8d16481e4fa266289fe64a124d3c042875d7805acd335d9e   #[linux]

requirements:
  build:
  run:

about:
  summary: An ultrafast optimal aligner for mapping large NGS data to large genome databases.
  home: https://github.com/knights-lab/BURST
  license: AGPL
