package:
  name: ninja_ops
  version: '1.5.1'

source:
  git_url: https://github.com/bhillmann/NINJA-OPS.git


build:
  entry_points:
      - ninja_ops = ninja_ops.ninja:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - argparse
    - argcomplete
    - bowtie2