{% set version = "0.9.8" %}

package:
  name: "shi7"
  version: "{{ version }}"

source:
  git_url: https://github.com/knights-lab/shi7.git
  git_rev: v{{ version }}

requirements:
  build:
    - python >=2.7
    - setuptools
    - gcc # [linux]
  run:
    - python >=2.7
    - trimmomatic
    - flash

build:
  number: 0

about:
  summary: SHort-read Iterative Trimmer with Learning Module
  license: AGPL
  license_file: LICENSE.md

test:
  commands:
    - shi7 --help
    - shi7_learning --help
