package:
  name: "shi7"
  version: "0.9.4"

source:
  git_url: https://github.com/knights-lab/shi7.git
  git_rev: v0.9.4

requirements:
  build:
    - python >=2.7
    - setuptools
    - gcc # [linux]
  run:
    - python >=2.7
    - trimmomatic
    - flash

build:
  number: 0

about:
  license: AGPL
  license_file: LICENSE.md

test:
  commands:
    - shi7 --help
    - shi7_learning --help
