{% set version = "1.0.3" %}

package:
  name: "shi7"
  version: "{{ version }}"

source:
  git_url: https://github.com/knights-lab/shi7.git
  git_rev: v{{ version }}

requirements:
  build:
    - python >=3
    - setuptools
  run:
    - python >=3
    - trimmomatic
    - flash

about:
  summary: SHort-read Iterative Trimmer with Learning Module
  license: AGPL
  license_file: LICENSE.md

test:
  commands:
    - shi7 --help
    - shi7_learning --help
