package:
  name: ninja_ops
  version: "0.0.1"

source:
  git_url: https://github.com/bhillmann/NINJA-OPS.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - bowtie2
