package:
  name: ninja_ops
  version: "0.0.1"

source:
  git_url: https://github.com/bhillmann/NINJA-OPS.git
  git_rev: 4cad9134b1dc5d5fa0f4fea11d01e749fd4c8f6c

requirements:
  build:
    - python
    - setuptools
  run:
    - python
