package:
  name: ninja_trebuchet
  version: "0.0.1"

source:
  git_url: https://github.com/bhillmann/NINJA-TREBUCHET.git
  git_rev: 5eac5021e110a791f74e52d1f9ca31d58c499b0a

requirements:
  build:
    - python
    - setuptools
    - click
  run:
    - python
    - click

    
about:
  license: BSD
  license_file: COPYING.txt
