{% set version = "1.0.6" %}

package:
  name: shogun
  version: "{{ version }}"

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/knights-lab/SHOGUN/archive/v{{ version }}.tar.gz
  sha256: 5457ED7DF19FB79036A0DB51035D05FE396397A43403198EDBB0417291766478

requirements:
  build:
    - python >=3
    - setuptools
    - pip
    - sphinx
    - click
    - pyyaml
    - numpy
    - cytoolz
    - pandas
    - scipy
  run:
    - python >=3
    - click
    - pyyaml
    - numpy
    - cytoolz
    - pandas
    - scipy
    - utree >=2.0rf
    - burst >=0.99.7f
    - bowtie2

about:
  summary: Accurate, scalable metagenomic quantification with shallow shotgun sequencing
  license: AGPL
  license_file: LICENSE.md
