{% set version = "1.0.8" %}

package:
  name: shogun
  version: "{{ version }}"

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/knights-lab/SHOGUN/archive/v{{ version }}.tar.gz
  sha256: f8e2f71ab7f08a6c247303ee5a9662e8e56323cd6b45c4416201b132e19b1376

requirements:
  build:
    - python >=3
    - setuptools
    - pip
    - sphinx
    - click
    - pyyaml
    - numpy
    - cytoolz
    - pandas
    - scipy
  run:
    - python >=3
    - click
    - pyyaml
    - numpy
    - cytoolz
    - pandas
    - scipy
    - utree >=2.0rf
    - burst >=0.99.7f
    - bowtie2

about:
  summary: Accurate, scalable metagenomic quantification with shallow shotgun sequencing
  license: AGPL
  license_file: LICENSE.md
