package:
  name: shogun
  version: "1.0.0"

source:
  fn: v1.0.0.tar.gz
  url: https://github.com/knights-lab/SHOGUN/archive/v1.0.0.tar.gz
  sha256: 03d8acca5a53c8e5f16a34522e2f017cc44bb3c03fd4d143034f4ac82acd7e40

requirements:
  build:
    - python >= 3
    - setuptools
    - pip
  run:
    - python >= 3
    - click
    - pyyaml
    - numpy
    - cytoolz
    - pandas
    - scipy
    - utree
    - burst

    
about:
  license: AGPL
  license_file: LICENSE.md
